[project]
name = "2025-coding-challenge-stackit-cloud-accelerator"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "pydantic>=2.11.7",
    "pytest>=8.4.1",
]
